export const DEFAULT_MENU = {
  "Burgers": [
    { name: "Dragon Classic Burger", price: 350 },
    { name: "Dragon Zinger Burger", price: 420 },
    { name: "Dragon Double Patty Burger", price: 550 },
    { name: "Dragon Cheese Burger", price: 400 },
    { name: "Dragon Crispy Chicken Burger", price: 380 },
    { name: "Dragon Fish Burger", price: 450 },
    { name: "Dragon Tower Burger", price: 650 },
    { name: "Dragon Beef Burger", price: 400 },
  ],
  "Fast Food": [
    { name: "Dragon Hot Wings (6 pcs)", price: 350 },
    { name: "Dragon Hot Wings (12 pcs)", price: 650 },
    { name: "Crispy Chicken Strips (4 pcs)", price: 400 },
    { name: "French Fries (Regular)", price: 150 },
    { name: "French Fries (Large)", price: 250 },
    { name: "Loaded Fries", price: 350 },
    { name: "Onion Rings", price: 200 },
    { name: "Club Sandwich", price: 420 },
  ],
  "Shawarma": [
    { name: "Chicken Shawarma (Small)", price: 180 },
    { name: "Chicken Shawarma (Large)", price: 280 },
    { name: "Zinger Shawarma", price: 320 },
    { name: "Crispy Shawarma", price: 350 },
    { name: "Beef Shawarma", price: 300 },
    { name: "Special Dragon Shawarma", price: 400 },
  ],
  "Rolls": [
    { name: "Chicken Roll", price: 250 },
    { name: "Crispy Chicken Roll", price: 300 },
    { name: "Beef Roll", price: 280 },
    { name: "Cheese Chicken Roll", price: 350 },
    { name: "Dragon Special Roll", price: 380 },
  ],
  "BBQ": [
    { name: "Chicken Tikka", price: 200 },
    { name: "Beef Seekh Kabab", price: 220 },
    { name: "Malai Botti", price: 250 },
    { name: "Chicken Botti", price: 200 },
    { name: "Chicken Reshmi Kabab", price: 220 },
  ],
  "Deals": [
    { name: "Deal 1 - Zinger + Fries + Drink", price: 650 },
    { name: "Deal 2 - 2 Burgers + Fries + 2 Drinks", price: 1100 },
    { name: "Deal 3 - Tower Burger + Fries + Drink", price: 750 },
    { name: "Deal 4 - 6 Wings + Fries + Drink", price: 600 },
    { name: "Deal 5 - 4 Shawarma + Fries + 2 Drinks", price: 1200 },
    { name: "Deal 6 - Family Bucket (12 Wings + 4 Burgers + Fries)", price: 2500 },
    { name: "Deal 7 - 2 Zinger + 2 Rolls + 2 Drinks", price: 1400 },
  ],
  "Drinks": [
    { name: "Pepsi / 7Up / Dew (Can)", price: 80 },
    { name: "Pepsi / 7Up / Dew (1.5L)", price: 200 },
    { name: "Water Bottle", price: 50 },
    { name: "Lassi (Sweet)", price: 150 },
    { name: "Mojito", price: 200 },
    { name: "Dragon Special Shake", price: 300 },
  ],
}
